; ModuleID = 'BitcodeBuffer'
source_filename = "beat_souper_fingerprint"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux4.19.0-gnu2.39.0"

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!42, !43}

!0 = distinct !DICompileUnit(language: DW_LANG_C99, file: !1, producer: "zig 0.14.1", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, globals: !30, splitDebugInlining: false)
!1 = !DIFile(filename: "beat_souper_fingerprint", directory: "/mnt/c/Users/matth/Documents/Repos/Beat.zig/src")
!2 = !{!3, !19, !25}
!3 = !DICompositeType(tag: DW_TAG_enumeration_type, name: "builtin.CompilerBackend", scope: !4, file: !4, line: 1069, baseType: !5, size: 64, align: 64, elements: !6)
!4 = !DIFile(filename: "builtin.zig", directory: "/snap/zig/14333/lib/std")
!5 = !DIBasicType(name: "u64", size: 64, encoding: DW_ATE_unsigned)
!6 = !{!7, !8, !9, !10, !11, !12, !13, !14, !15, !16, !17, !18}
!7 = !DIEnumerator(name: "other", value: 0, isUnsigned: true)
!8 = !DIEnumerator(name: "stage1", value: 1, isUnsigned: true)
!9 = !DIEnumerator(name: "stage2_llvm", value: 2, isUnsigned: true)
!10 = !DIEnumerator(name: "stage2_c", value: 3, isUnsigned: true)
!11 = !DIEnumerator(name: "stage2_wasm", value: 4, isUnsigned: true)
!12 = !DIEnumerator(name: "stage2_arm", value: 5, isUnsigned: true)
!13 = !DIEnumerator(name: "stage2_x86_64", value: 6, isUnsigned: true)
!14 = !DIEnumerator(name: "stage2_aarch64", value: 7, isUnsigned: true)
!15 = !DIEnumerator(name: "stage2_x86", value: 8, isUnsigned: true)
!16 = !DIEnumerator(name: "stage2_riscv64", value: 9, isUnsigned: true)
!17 = !DIEnumerator(name: "stage2_sparc64", value: 10, isUnsigned: true)
!18 = !DIEnumerator(name: "stage2_spirv64", value: 11, isUnsigned: true)
!19 = !DICompositeType(tag: DW_TAG_enumeration_type, name: "builtin.OutputMode", scope: !4, file: !4, line: 832, baseType: !20, size: 8, align: 8, elements: !21)
!20 = !DIBasicType(name: "u2", size: 8, encoding: DW_ATE_unsigned)
!21 = !{!22, !23, !24}
!22 = !DIEnumerator(name: "Exe", value: 0, isUnsigned: true)
!23 = !DIEnumerator(name: "Lib", value: 1, isUnsigned: true)
!24 = !DIEnumerator(name: "Obj", value: 2, isUnsigned: true)
!25 = !DICompositeType(tag: DW_TAG_enumeration_type, name: "builtin.LinkMode", scope: !4, file: !4, line: 840, baseType: !26, size: 8, align: 8, elements: !27)
!26 = !DIBasicType(name: "u1", size: 8, encoding: DW_ATE_unsigned)
!27 = !{!28, !29}
!28 = !DIEnumerator(name: "static", value: 0, isUnsigned: true)
!29 = !DIEnumerator(name: "dynamic", value: 1, isUnsigned: true)
!30 = !{!31, !34, !38, !40}
!31 = !DIGlobalVariableExpression(var: !32, expr: !DIExpression())
!32 = distinct !DIGlobalVariable(name: "zig_backend", linkageName: "builtin.zig_backend", scope: !33, file: !33, line: 6, type: !3, isLocal: true, isDefinition: true)
!33 = !DIFile(filename: "builtin.zig", directory: "/home/matth/.cache/zig/b/f2e3366d38f8c82ec265f1f7d2e49b83")
!34 = !DIGlobalVariableExpression(var: !35, expr: !DIExpression())
!35 = distinct !DIGlobalVariable(name: "simplified_logic", linkageName: "start.simplified_logic", scope: !36, file: !36, line: 17, type: !37, isLocal: true, isDefinition: true)
!36 = !DIFile(filename: "start.zig", directory: "/snap/zig/14333/lib/std")
!37 = !DIBasicType(name: "bool", size: 8, encoding: DW_ATE_boolean)
!38 = !DIGlobalVariableExpression(var: !39, expr: !DIExpression())
!39 = distinct !DIGlobalVariable(name: "output_mode", linkageName: "builtin.output_mode", scope: !33, file: !33, line: 8, type: !19, isLocal: true, isDefinition: true)
!40 = !DIGlobalVariableExpression(var: !41, expr: !DIExpression())
!41 = distinct !DIGlobalVariable(name: "link_mode", linkageName: "builtin.link_mode", scope: !33, file: !33, line: 9, type: !25, isLocal: true, isDefinition: true)
!42 = !{i32 2, !"Debug Info Version", i32 3}
!43 = !{i32 7, !"Dwarf Version", i32 4}
